"""Playlist export endpoints.

Spotify export runs server-side: we hold the user's tokens and call the Web
API directly. Apple Music export runs entirely in the browser via MusicKit JS;
this module only exposes the dev token, defined in routers/auth.py.
"""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from setplot import store
from setplot.server.auth import spotify as spotify_auth
from setplot.services import spotify as spotify_api

router = APIRouter(tags=["export"])


class SpotifyExportRequest(BaseModel):
    set_id: str
    name: str | None = None
    public: bool = False
    min_score: int = 0  # include all merged tracks by default


def _load_merged(set_id: str) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    if not store.set_dir(set_id).exists():
        raise HTTPException(status_code=404, detail=f"set {set_id} not found")
    meta = store.read_metadata(set_id)
    tracks_path = store.step_output_path(set_id, "fingerprint")
    if not tracks_path.exists():
        raise HTTPException(status_code=409, detail="fingerprinting hasn't run for this set yet")
    import json
    doc = json.loads(Path(tracks_path).read_text())
    return meta, doc.get("merged") or []


@router.get("/export/tracks/{set_id}")
async def list_tracks_for_export(set_id: str, min_score: int = 0) -> dict[str, Any]:
    """Tracks the apple-export.js client-side flow needs: title, artist, ISRC,
    apple_id (if any). Server filters by score and dedups by (title,artist,isrc)."""
    meta, merged = _load_merged(set_id)
    seen: set[tuple[str, str, str]] = set()
    out: list[dict[str, Any]] = []
    for t in merged:
        if int(t.get("score") or 0) < min_score:
            continue
        key = ((t.get("title") or "").lower(), (t.get("artists") or "").lower(), t.get("isrc") or "")
        if key in seen:
            continue
        seen.add(key)
        out.append({
            "title": t.get("title") or "",
            "artists": t.get("artists") or "",
            "isrc": t.get("isrc") or "",
            "apple": t.get("apple") or "",
            "spotify": t.get("spotify") or "",
            "score": int(t.get("score") or 0),
        })
    return {"set_title": meta.get("title") or set_id, "tracks": out}


@router.post("/export/spotify")
async def export_spotify(req: SpotifyExportRequest) -> dict[str, Any]:
    token = spotify_auth.get_valid_access_token()
    if not token:
        raise HTTPException(status_code=401, detail="not connected to spotify")

    meta, merged = _load_merged(req.set_id)
    candidates = [t for t in merged if int(t.get("score") or 0) >= req.min_score]
    if not candidates:
        raise HTTPException(status_code=400, detail="no tracks to export at this score threshold")

    matched_uris: list[str] = []
    seen: set[str] = set()  # de-dup the same Spotify URI showing up under multiple ACR windows
    unmatched: list[dict[str, Any]] = []
    resolution_breakdown = {"acr_id": 0, "isrc": 0, "search": 0, "unmatched": 0}
    for tk in candidates:
        uri, reason = spotify_api.resolve_track(token, tk)
        resolution_breakdown[reason] += 1
        if uri and uri not in seen:
            matched_uris.append(uri)
            seen.add(uri)
        elif not uri:
            unmatched.append({"title": tk.get("title"), "artists": tk.get("artists"), "isrc": tk.get("isrc", "")})

    if not matched_uris:
        raise HTTPException(status_code=400, detail="couldn't resolve any tracks on spotify")

    name = req.name or f"{meta.get('title') or 'SetPlot'} — recognized tracks"
    today = datetime.date.today().isoformat()
    description = f"Generated by SetPlot on {today} from {meta.get('title') or req.set_id}"
    pl = spotify_api.create_playlist(token, name, description, req.public)
    spotify_api.add_tracks(token, pl["id"], matched_uris)

    return {
        "playlist_url": (pl.get("external_urls") or {}).get("spotify") or "",
        "playlist_id": pl.get("id"),
        "matched": len(matched_uris),
        "unmatched": unmatched,
        "resolution": resolution_breakdown,
    }
